export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const SHOW_ALERT = 'SHOW_ALERT';
export const UPDATE_TOTAL_DONATE = 'UPDATE_TOTAL_DONATE';
export const SET_PAYMENTS = 'SET_PAYMENTS';
export const SET_CHARITIES = 'SET_CHARITIES';
export const SHOW_AMOUNTS = 'SHOW_AMOUNTS';
export const SELECT_AMOUNT = 'SELECT_AMOUNT';
export const FETCH_FAIL = 'FETCH_FAIL';
